In [11]:
import torch

# Example tensor and mask
bs, block_size, embedding_dim = 2, 4, 3
tensor = torch.randn(bs, block_size, embedding_dim) * 100  # Shape: [bs, block_size, embedding_dim]
mask = torch.tensor([[True, False, True, False],    # Shape: [bs, block_size]
                     [False, True, False, True]])
print(mask.shape)

# Expand the mask to match the last dimension
mask_expanded = mask.unsqueeze(-1).expand(-1, -1, tensor.shape[2])  # Shape: [bs, block_size, embedding_dim]

# Zero out embeddings where mask is True
masked_tensor = tensor * mask_expanded
print("tensor:")
print(tensor, "\n")
print("masked:")
print(masked_tensor)
print("mask:")
print(mask_expanded)
print(4000 * False)
print(4000 * True)

torch.Size([2, 4])
tensor:
tensor([[[ 141.2151, -152.0132, -181.6751],
         [  49.9806, -151.2866,  -31.6955],
         [-113.1871,  144.5193,   70.9442],
         [-197.9320,  214.9752,   86.1488]],

        [[  56.5941,  -42.3545,  -74.8166],
         [ -76.1951,  107.5206,  247.5702],
         [  23.5869,  102.2235,  -21.7183],
         [  46.3556,   13.6169,   67.6697]]]) 

masked:
tensor([[[ 141.2151, -152.0132, -181.6751],
         [   0.0000,   -0.0000,   -0.0000],
         [-113.1871,  144.5193,   70.9442],
         [  -0.0000,    0.0000,    0.0000]],

        [[   0.0000,   -0.0000,   -0.0000],
         [ -76.1951,  107.5206,  247.5702],
         [   0.0000,    0.0000,   -0.0000],
         [  46.3556,   13.6169,   67.6697]]])
mask:
tensor([[[ True,  True,  True],
         [False, False, False],
         [ True,  True,  True],
         [False, False, False]],

        [[False, False, False],
         [ True,  True,  True],
         [False, False, False],
         [ True,  T